name: wui_flutter
description: "A new wajek wui package for flutter project"
version: 0.0.1
homepage: https://github.com/mochrira/wui_flutter

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/inter/InterDisplay-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/inter/InterDisplay-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/inter/InterDisplay-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/inter/InterDisplay-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/inter/InterDisplay-Italic.ttf
  #         style: italic
  #         weight: 400
  #       - asset: assets/fonts/inter/InterDisplay-MediumItalic.ttf
  #         style: italic
  #         weight: 500
  #       - asset: assets/fonts/inter/InterDisplay-SemiBoldItalic.ttf
  #         style: italic
  #         weight: 600
  #       - asset: assets/fonts/inter/InterDisplay-BoldItalic.ttf
  #         style: italic
  #         weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
